{% set version = "0.2.0" %}

package:
  name: notebook-shim
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook-shim/notebook_shim-{{ version }}.tar.gz
  sha256: fdb81febb05932c6d19e44e10382ce05469cac5e1b6e99b49be6159ddb5e4804

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling >=1.0
    - pip
    - python >=3.7
  run:
    - jupyter_server >=1.8,<3
    - python >=3.7

test:
  imports:
    - notebook_shim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/notebook_shim
  summary: A shim layer for notebook traits and config
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - Zsailer
