{% set name = "notebook-shim" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/notebook_shim-{{ version }}.tar.gz
  sha256: f69388ac283ae008cd506dda10d0288b09a017d822d5e8c7129a152cbd3ce7e9

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python
    - hatchling >=1.0
    - pip
  run:
    - python
    - jupyter_server >=1.8,<3

test:
  imports:
    - notebook_shim
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter/notebook_shim
  summary: A shim layer for notebook traits and config
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    This project provides a way for JupyterLab and other frontends to switch to Jupyter Server for their Python Web application backend.
  doc_url: https://github.com/jupyter/notebook_shim/blob/main/README.md
  dev_url: https://github.com/jupyter/notebook_shim

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - Zsailer
